print("Hello (*/ω＼*)")
print("I'm Raphael Jedidiah R. Borillo")
print("My course is BCS12")
print("Nice to meet you! ╰(*°▽°*)╯")
print("")
print("**********   *       *  *************  *      *       ******      *      *")
print("*        *    *     *         *        *      *     *        *    **     *")
print("*        *     *   *          *        *      *     *        *    * *    *")
print("**********       *            *        ********     *        *    *  *   *")
print("*                *            *        *      *     *        *    *   *  *")
print("*                *            *        *      *     *        *    *    * *")
print("*                *            *        *      *       ******      *     **")
